### PR TITLE
migrated hardhat

### PR DESCRIPTION
**Pull request by Pfed-prog**
https://hardhat.org/hardhat-chai-matchers/docs/migrate-from-waffle

:link: [zboto Link](https://app.clickup.com/t/8677bdnfr)

### CODE REVIEW

**Comment by emmanuelm41** [comment]
@Pfed-prog there is an issue with running tests for external contributor. We asked GitHub about it. As soon as they fix it, we will trigger tests and merge it if they pass! Hold on there please!

**Comment by emmanuelm41** [comment]
@Pfed-prog could you set the hardhat private key so it has some account with funds to run the hardhat tests? That should be enough to merge the PR.

**Comment by Pfed-prog** [comment]
> @Pfed-prog could you set the hardhat private key so it has some account with funds to run the hardhat tests? That should be enough to merge the PR.

I am not really sure where to store the private key, should i change something in my repository github evvironment or hardcode variable in the `.env` file directly

**Comment by emmanuelm41** [comment]
> > @Pfed-prog could you set the hardhat private key so it has some account with funds to run the hardhat tests? That should be enough to merge the PR.
> 
> I am not really sure where to store the private key, should i change something in my repository GitHub environment or hard code variable in `.env` file directly

You should add it here (under your forked repo config)
image

**Comment by Pfed-prog** [comment]
Added a private_key and transferred 5 TFIL via faucet
image

**Comment by emmanuelm41** [comment]
@Pfed-prog please, re run the CI and it should work!

**Comment by Pfed-prog** [comment]
> @Pfed-prog please, re run the CI and it should work!

I apologize I am not sure how to accomplish this

**Comment by emmanuelm41** [comment]
> > @Pfed-prog please, re run the CI and it should work!
> 
> I apologize I am not sure how to accomplish this

A new commit on the PR please!

**Comment by Pfed-prog** [comment]
It fails once again, maybe i need to add it into an environment

**Comment by emmanuelm41** [comment]
> It fails once again, maybe i need to add it into an environment

It should be something like this  "0746ce973d40a0f89c72xxxxxxxxxxxx2f95fc7e" (32 bytes long, 64 hex string)

**Comment by Pfed-prog** [comment]
Sure, added "57cb47da57d864f5f1b0de38c7e4a2ab12ede9d8b4bd???68966da0dcdbc7309", but with this commit added ""

**Comment by Pfed-prog** [comment]
checked the history of commits once again i think without "" actually passed
image

**Pull request merged**
