### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by orenyomtov**
:link: [zboto Link](https://app.clickup.com/t/8677rnd10)

### CODE REVIEW

**Comment by rllola** [comment]
Hey @orenyomtov 
Could give me some more context for this change ?

**Comment by orenyomtov** [comment]
If I'm not mistaken, the original comment was wrong, so I fixed it

The precompile by default calls the actor, and does not delegate call it

**Comment by rllola** [comment]
We do use delegated call opcode for it so we are doing a delegated call like the comment originally mentioned.

**Comment by orenyomtov** [comment]
Yeah you always delegatecall to the precompile, and then the precompile either calls or static-calls, depending on the flag provided

**Comment by rllola** [comment]
Ah yes indeed you are right! Nice lets get this merge.

**Pull request merged**
