### PR TITLE
test: VerifiedReg actor and test for AddVerifiedClient and GetClaims

### PR DESCRIPTION
**Pull request by neithanmo**
:link: [zboto Link](https://app.clickup.com/t/86770cuy3)

### CODE REVIEW

**Comment by rllola** [comment]
You are still missing
- `get_claims`
- `remove_expired_allocations`
- `extend_claim_terms`
- `remove_expired_claims`

You don't need to have the proper serialized params or exit code 0. I will fix them after.

**Review by rllola — APPROVED** [review]
We can merge this and we will fix the setup in an other PR.

**Comment by rllola** [comment]
I am afraid this is going to be difficult to merge now. We should prefer rebasing when doing PR instead of merging.

**Comment by neithanmo** [comment]
lets close this in order to open a new one which would include the latest changes.

**Pull request closed without merging**
